### ISSUE TITLE
Apply to Lorentz Centre?

### ISSUE THREAD

**Issue by dhuppenkothen** [AstroHackWeek/AstroHackWeek2018#11]
If we would want to run AstroHackWeek at the Lorentz Centre:

The next application deadline is **September 15**, so we'd have to turn around and basically apply right after the end of this hack week. 

Instructions are here: http://www.lorentzcenter.nl/proposals.php
There are weeks available next autumn: http://www.lorentzcenter.nl/timeslots.php
In particular: 6 Aug-10 Aug, 13 Aug-17 Aug, 20 Aug-24 Aug, all of September

It would have to be the "Oort" venue, which has space for up to 55 people. 

I think we could hack a convincing proposal together in a fairly short amount of time repurposing text from the website, the hack week paper and the various documents/blog posts/funding reports we've written about Astro Hack Week.

I am happy to supply useful documents and data and help where I can, but I couldn't take the lead on this if we decided to move forward with it.

**Comment by davidwhogg** [comment]
I think this can be closed, no?

**Comment by dhuppenkothen** [comment]
Yes. Closing.
