### ISSUE TITLE
LSSTC grants? Apply early!

### ISSUE THREAD

**Issue by dhuppenkothen** [AstroHackWeek/AstroHackWeek2018#6]

**Comment by dhuppenkothen** [comment]
Deadline for applications is **Dec 18, 2017**. 

More details here: https://www.lsstcorporation.org/2018-Call-for-Proposals

**Comment by davidwhogg** [comment]
Uhhh.. Did we make this? Close or update.

**Comment by dhuppenkothen** [comment]
Yes, proposal got submitted. Closing.

**Comment by davidwhogg** [comment]
You rock.
